package io.sagaweaw.core;

import java.util.Map;
import java.util.Optional;

/**
 * Contract that every Saga context class must implement.
 *
 * The context is the data envelope that travels through the entire Saga —
 * from the initial trigger through every step and compensation.
 * Implement it as a Record for simple contexts or a class with final fields
 * when steps need to accumulate data.
 *
 * <pre>
 * public record OrderContext(
 *     String     orderId,
 *     String     customerId,
 *     BigDecimal amount
 * ) implements SagaContext {}
 *
 * sagaManager.start(OrderSaga.class, new OrderContext("order-123", "cust-456", BigDecimal.TEN));
 * </pre>
 *
 * Step outputs (e.g. an ID generated by a step) are NOT stored here — they are captured
 * by the engine in saga_steps.payload and exposed to compensations via StepOutput.
 *
 * @see StepOutput
 */
public interface SagaContext {

    /**
     * Optional business identifier shown in the dashboard instead of the saga UUID.
     *
     * Examples:
     *   "order #48291"
     *   "payment $150.00 → john@acme.com"
     *   "user onboarding user-7842"
     */
    default Optional<String> businessKey() {
        return Optional.empty();
    }

    /**
     * Arbitrary key-value metadata stored with the saga for tracing and audit.
     * These appear in the dashboard and event log but play no role in execution.
     *
     * Examples:
     *   "tenant"        -> "fintech-abc"
     *   "channel"       -> "mobile-app"
     *   "correlationId" -> "req-xyz-789"
     */
    default Map<String, String> metadata() {
        return Map.of();
    }
}
