spring.application.name=order-saga-example

spring.datasource.url=jdbc:postgresql://localhost:5432/sagaweaw
spring.datasource.username=sagaweaw
spring.datasource.password=sagaweaw
spring.jpa.hibernate.ddl-auto=none

spring.kafka.bootstrap-servers=localhost:9092

server.port=8080

sagaweaw.observability.token=${SAGAWEAW_TOKEN}
